#!/bin/bash
#----------------------------------------------------
# Example SLURM job script to run OpenMP applications
# on TACC's Stampede system.
#----------------------------------------------------
#SBATCH -J pass_runner       # Job name
#SBATCH -o pass_runner.o%j   # Name of stdout output file(%j expands to jobId)
#SBATCH -e pass_runner.err.o%j   # Name of stderr output file(%j expands to jobId)
#SBATCH -p development           # Submit to the 'normal' or 'development' queue
#SBATCH -N 16                # Total number of nodes requested (20 cores/node)
#SBATCH -n 16                # Total number of mpi tasks requested
#SBATCH -t 02:00:00         # Run time (hh:mm:ss) - 1.5 hours
## The next line is required if the user has more than one project
#SBATCH -A Galois  # Allocation name to charge job against
 

module load llvm
 
# Set the number of threads per task(Default=1)
export OMP_NUM_THREADS=16
time ./ev2 matrix.o 300 16  
echo "------------";
export OMP_NUM_THREADS=8
time ./ev2 matrix.o 300 8
echo "-----------";
export OMP_NUM_THREADS=4
time ./ev2 matrix.o 300 4  
echo "-----------";
export OMP_NUM_THREADS=1
time ./ev2 matrix.o 300 1  
echo "-----------";
