#!/bin/bash

opt -stats -load ./ModuleInfo.so -module-info ../object_files/$1 -o temp-files/$1-out.bc &> temp-files/$1.temp

cat temp-files/$1.temp  | grep "STAT" |  awk 'BEGIN { ORS = " " } { print$1 }' > results/$1.results
