#!/bin/bash
#----------------------------------------------------
# Example SLURM job script to run OpenMP applications
# on TACC's Stampede system.
#----------------------------------------------------
#SBATCH -J pass_runner       # Job name
#SBATCH -o pass_runner-de.o%j   # Name of stdout output file(%j expands to jobId)
#SBATCH -e pass_runner-de.err.o%j   # Name of stderr output file(%j expands to jobId)
#SBATCH -p development           # Submit to the 'normal' or 'development' queue
#SBATCH -N 1                # Total number of nodes requested (20 cores/node)
#SBATCH -n 16                # Total number of mpi tasks requested
#SBATCH -t 02:00:00         # Run time (hh:mm:ss) - 1.5 hours
## The next line is required if the user has more than one project
#SBATCH -A Galois  # Allocation name to charge job against
 

module load llvm
 
# Set the number of threads per task(Default=1)
export OMP_NUM_THREADS=16

#./ev2 prog1.o xaa " xaadir/test" 24 2> xaa_output 1>/dev/null

#./ev2 prog1.o xab " xabdir/test" 16 2> xab_output 1>/dev/null
#./ev2 prog1.o xac " xacdir/test" 16 2> xac_output 1>/dev/null
#./ev2 prog1.o xad " xaddir/test" 16 2> xad_output 1>/dev/null


send "got the queue."
./ev2 prog4.o xaa " xaadir/test" 24 2> ../prog4/xaa_output 1>/dev/null
./ev2 prog4.o xab " xabdir/test" 24 2> ../prog4/xab_output 1>/dev/null
send "Ran for expected jobs"
./ev2 prog4.o xac " xacdir/test" 24 2> ../prog4/xac_output 1>/dev/null
./ev2 prog4.o xad " xaddir/test" 24 2> ../prog4/xad_output 1>/dev/null
send "Ran for unexpected jobs"


#./ev2 ./prog3.o xaa " xaadir/test" 24 2> ../prog3/xaa_output 1>/dev/null
#./ev2 ./prog3.o xab " xabdir/test" 24 2> ../prog3/xab_output 1>/dev/null
#./ev2 ./prog3.o xac " xacdir/test" 24 2> ../prog3/xac_output 1>/dev/null
#./ev2 ./prog3.o xad " xaddir/test" 24 2> ../prog3/xad_output 1>/dev/null

