#!/bin/bash
#----------------------------------------------------
# Example SLURM job script to run OpenMP applications
# on TACC's Stampede system.
#----------------------------------------------------
#SBATCH -J pass_runner       # Job name
#SBATCH -o pass_runner-de.o%j   # Name of stdout output file(%j expands to jobId)
#SBATCH -e pass_runner-de.err.o%j   # Name of stderr output file(%j expands to jobId)
#SBATCH -p normal           # Submit to the 'normal' or 'development' queue
#SBATCH -N 1                # Total number of nodes requested (20 cores/node)
#SBATCH -n 16                # Total number of mpi tasks requested
#SBATCH -t 48:00:00         # Run time (hh:mm:ss) - 1.7 hours
## The next line is required if the user has more than one project
#SBATCH -A Galois  # Allocation name to charge job against
 

module load llvm
 
# Set the number of threads per task(Default=1)
export OMP_NUM_THREADS=16

#./ev2 prog1.o xaa " xaadir/test" 24 2> xaa_output 1>/dev/null

#./ev2 prog1.o xab " xabdir/test" 16 2> xab_output 1>/dev/null
#./ev2 prog1.o xac " xacdir/test" 16 2> xac_output 1>/dev/null
#./ev2 prog1.o xad " xaddir/test" 16 2> xad_output 1>/dev/null


## 5 taking lot of time


send "got the NORMAL queue"
./ev2 prog9.o xaa " xaadir/test" 16 2> prog9_xaa_output 1>/dev/null
./ev2 prog9.o xab " xabdir/test" 16 2> prog9_xab_output 1>/dev/null
./ev2 prog9.o xac " xacdir/test" 16 2> prog9_xac_output 1>/dev/null
./ev2 prog9.o xad " xaddir/test" 16 2> prog9_xad_output 1>/dev/null
send "RAN 1 GIANT JOB"

./ev2 prog8.o xaa " xaadir/test" 16 2> prog8_xaa_output 1>/dev/null
./ev2 prog8.o xab " xabdir/test" 16 2> prog8_xab_output 1>/dev/null
./ev2 prog8.o xac " xacdir/test" 16 2> prog8_xac_output 1>/dev/null
./ev2 prog8.o xad " xaddir/test" 16 2> prog8_xad_output 1>/dev/null
send "RAN 2 GIANT JOB"

./ev2 prog19.o xaa " xaadir/test" 16 2> prog19_xaa_output 1>/dev/null
./ev2 prog19.o xab " xabdir/test" 16 2> prog19_xab_output 1>/dev/null
./ev2 prog19.o xac " xacdir/test" 16 2> prog19_xac_output 1>/dev/null
./ev2 prog19.o xad " xaddir/test" 16 2> prog19_xad_output 1>/dev/null

send "RAN 3 GIANT JOB"

./ev2 prog20.o xaa " xaadir/test" 16 2> prog20_xaa_output 1>/dev/null
./ev2 prog20.o xab " xabdir/test" 16 2> prog20_xab_output 1>/dev/null
./ev2 prog20.o xac " xacdir/test" 16 2> prog20_xac_output 1>/dev/null
./ev2 prog20.o xad " xaddir/test" 16 2> prog20_xad_output 1>/dev/null





#./ev2 ./prog3.o xaa " xaadir/test" 24 2> ../prog3/xaa_output 1>/dev/null
#./ev2 ./prog3.o xab " xabdir/test" 24 2> ../prog3/xab_output 1>/dev/null
#./ev2 ./prog3.o xac " xacdir/test" 24 2> ../prog3/xac_output 1>/dev/null
#./ev2 ./prog3.o xad " xaddir/test" 24 2> ../prog3/xad_output 1>/dev/null

